version: '3.9'

services:
    front:
        env_file:
            - .env
        build: .
        container_name: front
        restart: unless-stopped
        ports:
            - 3000:3000
        networks:
            - nginxproxyman

networks:
    nginxproxyman:
        external: true
